version: '3.1'
services:
  springapp:
    container_name: springapp
    image: ravshan1972/spring-boot-mongo:1
    ports:
    - 9090:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@1306
    networks:
      - springappbridge
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@1306
    volumes:
      - mongodb:/data/db
    networks:
      - springappbridge
volumes:
  mongodb:
    name: mongodb
    driver: local
networks:
  springappbridge:
    name: springappbridge
    driver: bridge
